# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1listtopic():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1listtopic(self):
    # Test name: 1_list_topic
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://brand.netray.id/")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | css=.py-4 | 
    self.driver.find_element(By.CSS_SELECTOR, ".py-4").click()
    # 4 | verifyTitle | Topic List | Netray | 
    assert self.driver.title == "Topic List | Netray"
    # 5 | mouseOver | css=.generate-statistic-btn:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".generate-statistic-btn:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | css=.generate-statistic-btn:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | mouseOver | css=.btn:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOut | css=.btn:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | click | css=.font-weight-normal:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".font-weight-normal:nth-child(1)").click()
    # 10 | click | id=logo | 
    self.driver.find_element(By.ID, "logo").click()
    # 11 | click | css=.topic-list--twitter .mb-3 | 
    self.driver.find_element(By.CSS_SELECTOR, ".topic-list--twitter .mb-3").click()
    # 12 | click | css=.topic-list--twitter .mb-3 | 
    self.driver.find_element(By.CSS_SELECTOR, ".topic-list--twitter .mb-3").click()
    # 13 | mouseOver | css=.tooltips-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".tooltips-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | mouseOut | css=.tooltips-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 15 | mouseOver | css=.btn:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 16 | mouseOut | css=.btn:nth-child(2) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 17 | click | css=.btn:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    # 18 | click | css=.col-6:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-6:nth-child(1)").click()
    # 19 | close |  | 
    self.driver.close()
  
