# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2invalidusername():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2invalidusername(self):
    # Test name: 2_invalid_username
    # Step # | name | target | value
    # 1 | open | /login?redirect=%2F | 
    self.driver.get("https://brand.netray.id/login?redirect=%2F")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 4 | type | id=username | 12345
    self.driver.find_element(By.ID, "username").send_keys("12345")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | password123
    self.driver.find_element(By.ID, "password").send_keys("password123")
    # 7 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 8 | click | id=errorAlert | 
    self.driver.find_element(By.ID, "errorAlert").click()
    # 9 | click | id=errorAlert | 
    self.driver.find_element(By.ID, "errorAlert").click()
    # 10 | click | css=.close | 
    self.driver.find_element(By.CSS_SELECTOR, ".close").click()
    # 11 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 12 | type | id=password | password123
    self.driver.find_element(By.ID, "password").send_keys("password123")
    # 13 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 14 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 15 | type | id=password | password123
    self.driver.find_element(By.ID, "password").send_keys("password123")
    # 16 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 17 | close |  | 
    self.driver.close()
  
