# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test7validsignup():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_7validsignup(self):
    # Test name: 7_valid_sign_up
    # Step # | name | target | value
    # 1 | open | /login?redirect=%2F | 
    self.driver.get("https://brand.netray.id/login?redirect=%2F")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | id=signupButton | 
    self.driver.find_element(By.ID, "signupButton").click()
    # 4 | click | id=fullnameField | 
    self.driver.find_element(By.ID, "fullnameField").click()
    # 5 | type | id=fullnameField | testtest
    self.driver.find_element(By.ID, "fullnameField").send_keys("testtest")
    # 6 | click | id=usernameField | 
    self.driver.find_element(By.ID, "usernameField").click()
    # 7 | type | id=usernameField | testtest
    self.driver.find_element(By.ID, "usernameField").send_keys("testtest")
    # 8 | click | id=emailField | 
    self.driver.find_element(By.ID, "emailField").click()
    # 9 | type | id=emailField | testtest@test.com
    self.driver.find_element(By.ID, "emailField").send_keys("testtest@test.com")
    # 10 | click | id=passwordField | 
    self.driver.find_element(By.ID, "passwordField").click()
    # 11 | type | id=passwordField | testtest
    self.driver.find_element(By.ID, "passwordField").send_keys("testtest")
    # 12 | click | id=confirmPasswordField | 
    self.driver.find_element(By.ID, "confirmPasswordField").click()
    # 13 | type | id=confirmPasswordField | testtest
    self.driver.find_element(By.ID, "confirmPasswordField").send_keys("testtest")
    # 14 | click | id=phoneField | 
    self.driver.find_element(By.ID, "phoneField").click()
    # 15 | type | id=phoneField | 082111111
    self.driver.find_element(By.ID, "phoneField").send_keys("082111111")
    # 16 | click | css=.mb-3 > .custom-control-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-3 > .custom-control-label").click()
    # 17 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 18 | click | css=.recaptcha-checkbox-spinner-overlay | 
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-spinner-overlay").click()
    # 19 | selectFrame | relative=parent | 
    self.driver.switch_to.default_content()
    # 20 | click | id=registerButton | 
    self.driver.find_element(By.ID, "registerButton").click()
    # 21 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 22 | close |  | 
    self.driver.close()
  
