# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test1blanklogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1blanklogin(self):
    # Test name: 1_blank_login
    # Step # | name | target | value
    # 1 | open | /login?redirect=%2F | 
    self.driver.get("https://brand.netray.id/login?redirect=%2F")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 4 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 5 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 6 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 7 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 8 | doubleClick | id=loginButton | 
    element = self.driver.find_element(By.ID, "loginButton")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 9 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 10 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 11 | doubleClick | id=loginButton | 
    element = self.driver.find_element(By.ID, "loginButton")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    # 12 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 13 | close |  | 
    self.driver.close()
  
