# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4validlogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4validlogin(self):
    # Test name: 4_valid_login
    # Step # | name | target | value
    # 1 | open | /login?redirect=%2F | 
    self.driver.get("https://brand.netray.id/login?redirect=%2F")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 4 | type | id=username | mellyuga
    self.driver.find_element(By.ID, "username").send_keys("mellyuga")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | password123
    self.driver.find_element(By.ID, "password").send_keys("password123")
    # 7 | click | id=loginButton | 
    self.driver.find_element(By.ID, "loginButton").click()
    # 8 | click | id=userMenu__BV_toggle_ | 
    self.driver.find_element(By.ID, "userMenu__BV_toggle_").click()
    # 9 | click | css=.rounded-circle | 
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-circle").click()
    # 10 | close |  | 
    self.driver.close()
  
