# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test7allsentiment():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_7allsentiment(self):
    # Test name: 7_all_sentiment
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://brand.netray.id/")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | css=.list-inline | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-inline").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | click | id=__BVID__76 | 
    self.driver.find_element(By.ID, "__BVID__76").click()
    # 6 | runScript | window.scrollTo(0,1291) | 
    self.driver.execute_script("window.scrollTo(0,1291)")
    # 7 | mouseOver | css=.section:nth-child(2) .tooltips-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".section:nth-child(2) .tooltips-btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOut | css=.section:nth-child(2) .tooltips-btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | close |  | 
    self.driver.close()
  
