# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4datefilterthismonth():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4datefilterthismonth(self):
    # Test name: 4_date filter_this_month
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://brand.netray.id/")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | css=.topic-card-wrapper > .card-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".topic-card-wrapper > .card-body").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | click | css=.input-group | 
    self.driver.find_element(By.CSS_SELECTOR, ".input-group").click()
    # 6 | click | id=datePickerText | 
    self.driver.find_element(By.ID, "datePickerText").click()
    # 7 | click | css=.btn:nth-child(4) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | runScript | window.scrollTo(0,1239) | 
    self.driver.execute_script("window.scrollTo(0,1239)")
    # 10 | close |  | 
    self.driver.close()
  
