# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test3datefilterlast30():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_3datefilterlast30(self):
    # Test name: 3_date_filter_last_30
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://brand.netray.id/")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | css=.list-inline | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-inline").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | runScript | window.scrollTo(0,1319) | 
    self.driver.execute_script("window.scrollTo(0,1319)")
    # 6 | click | id=datePickerText | 
    self.driver.find_element(By.ID, "datePickerText").click()
    # 7 | click | css=.btn-primary:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary:nth-child(3)").click()
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | runScript | window.scrollTo(0,3249) | 
    self.driver.execute_script("window.scrollTo(0,3249)")
    # 10 | close |  | 
    self.driver.close()
  
