# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test2datefilterlast7():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_2datefilterlast7(self):
    # Test name: 2_date_filter_last_7
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://brand.netray.id/")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | css=.list-inline | 
    self.driver.find_element(By.CSS_SELECTOR, ".list-inline").click()
    # 4 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 5 | click | id=datePickerText | 
    self.driver.find_element(By.ID, "datePickerText").click()
    # 6 | click | css=.btn-block:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-block:nth-child(2)").click()
    # 7 | runScript | window.scrollTo(0,1243) | 
    self.driver.execute_script("window.scrollTo(0,1243)")
    # 8 | close |  | 
    self.driver.close()
  
