# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test5datefilterthisyear():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_5datefilterthisyear(self):
    # Test name: 5_date_filter_this year
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://brand.netray.id/")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | css=.topic-card-wrapper > .card-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".topic-card-wrapper > .card-body").click()
    # 4 | mouseOver | id=__BVID__51__BV_toggle_ | 
    element = self.driver.find_element(By.ID, "__BVID__51__BV_toggle_")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 6 | mouseOut | id=__BVID__51__BV_toggle_ | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | id=datePickerText | 
    self.driver.find_element(By.ID, "datePickerText").click()
    # 8 | click | css=.btn:nth-child(5) | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(5)").click()
    # 9 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 10 | runScript | window.scrollTo(0,1237) | 
    self.driver.execute_script("window.scrollTo(0,1237)")
    # 11 | close |  | 
    self.driver.close()
  
