# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test7hideentity():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_7hideentity(self):
    # Test name: 7_hide_entity
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://brand.netray.id/")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | click | css=.card-body > .justify-content-between | 
    self.driver.find_element(By.CSS_SELECTOR, ".card-body > .justify-content-between").click()
    # 4 | runScript | window.scrollTo(0,1262) | 
    self.driver.execute_script("window.scrollTo(0,1262)")
    # 5 | click | css=.section:nth-child(8) .list-group-item:nth-child(6) .btn | 
    self.driver.find_element(By.CSS_SELECTOR, ".section:nth-child(8) .list-group-item:nth-child(6) .btn").click()
    # 6 | mouseOver | css=.section:nth-child(8) .list-group-item:nth-child(6) .btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".section:nth-child(8) .list-group-item:nth-child(6) .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | css=.section:nth-child(8) .list-group-item:nth-child(6) .btn | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | click | css=.text-right > .btn-danger | 
    self.driver.find_element(By.CSS_SELECTOR, ".text-right > .btn-danger").click()
    # 9 | close |  | 
    self.driver.close()
  
